{
 "title": "Système & App Demo",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Taux de requêtes HTTP App pour 1min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(method) (rate(http_requests_total[1m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Charge CPU App",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "simulated_cpu_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Système",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}